name: Publish to nuget.org

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

jobs:
  publish: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
        
    - name: Create package  
      run: |
        cd ./FluentFunctionalCoding/FluentFunctionalCoding       
        dotnet restore
        dotnet build --configuration Release --no-restore
    - name: Publish the package to nuget repository
      run: |
        cd ./FluentFunctionalCoding/FluentFunctionalCoding/bin/Release
        ls -la
        dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.PUSH_TO_NUGET_ORG }}" --skip-duplicate

#jobs:
#publish: 
#    runs-on: ubuntu-latest
    
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: '7.0.x'
        
#    - name: Restore dependencies
#      run: dotnet restore      
#    - name: Build
#      run: dotnet build

            
#    - name: Publish the package to NUGET.ORG
#      run: dotnet nuget push */bin/Release/*.nupkg  -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
#      env:      
#        NUGET_AUTH_TOKEN: ${{ secrets.PUSH_TO_NUGET_ORG }}
